#!/bin/sh
set -ue

for hook in /etc/kernel/postrm.d/*; do
    if [ "$(basename "${hook}")" = '00disabled' ]; then
        continue
    else
        cat << 'EOT' > "${hook}"
#!/bin/sh
set -ue

exit 0
EOT
    fi
done
