on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: setup-mkosi
        uses: systemd/mkosi@da814d96341828ba573821577e2b973cdc16f91f
      - name: version
        run: |
          mkosi --version
      - name: summary
        run: |
          mkosi -d debian -r trixie summary --no-pager
      - name: build server
        run: |
          make
      - name: build desktop
        run: |
          make desktop
