on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: setup-mkosi
        uses: systemd/mkosi@main
      - name: build server
        run: |
          mkosi -d debian -r trixie build
      - name: build desktop
        run: |
          mkosi -d debian -r trixie --profile desktop build
