on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: setup-mkosi
        uses: systemd/mkosi@v25.3
      - name: build
        run: |
          mkosi -d debian -r trixie build
